name: pi_environment
channels:
  - defaults
  - conda-forge
  - rpi
  - intel

dependencies:
  - python=3.6
  - numpy
  - pandas
  - cython

  - pip:
    - jupyter
    - jupyterlab
    - pyHS100
    - flask
    - pybluez
    - w1thermsensor
    - Adafruit_DHT
    - RPi.GPIO
    - matplotlib
